apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reset-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reset
  minReplicas: 2
  maxReplicas: 9
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50